version: '3.8'

services:
  # База данных PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: supwork-postgres
    environment:
      POSTGRES_DB: supworkdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - supwork-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Eureka Server - Service Discovery
  eureka-server:
    build:
      context: ./supwork-eureka-server
      dockerfile: Dockerfile
    container_name: supwork-eureka-server
    ports:
      - "8761:8761"
    networks:
      - supwork-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8761/actuator/health || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s

  # API Gateway
  api-gateway:
    build:
      context: ./supwork-api-gateway
      dockerfile: Dockerfile
    container_name: supwork-api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - supwork-network
    restart: unless-stopped

  # User Service - Auth & User Management
  user-service:
    build:
      context: ./supwork-user-service
      dockerfile: Dockerfile
    container_name: supwork-user-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/supworkdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - supwork-network
    restart: unless-stopped

  # Gig Service - Order Management
  gig-service:
    build:
      context: ./supwork-gig-service
      dockerfile: Dockerfile
    container_name: supwork-gig-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - eureka-server
      - user-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/supworkdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - supwork-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  supwork-network:
    driver: bridge

