server:
  port: 8083

spring:
  application:
    name: search-service
  
  data:
    mongodb:
      uri: mongodb://localhost:27017/supworkdb
    
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: supwork-secret-key

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.supwork.search: DEBUG
    org.springframework.data.mongodb: DEBUG

# Resilience4j Configuration
resilience4j:
  circuitbreaker:
    instances:
      user-service:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 10
        minimum-number-of-calls: 5
      gig-service:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 10
        minimum-number-of-calls: 5
  timelimiter:
    instances:
      user-service:
        timeout-duration: 2s
      gig-service:
        timeout-duration: 2s
