server:
  port: 8082

spring:
  application:
    name: gig-service
  
  datasource:
    url: jdbc:postgresql://localhost:5433/supworkdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

jwt:
  secret: supwork-secret-key-please-change-in-production-min-256-bits

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.supwork.gig.service.UserClient: DEBUG
    org.springframework.cloud.openfeign: DEBUG

# Resilience4j Configuration
resilience4j:
  circuitbreaker:
    instances:
      user-service:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 10
        minimum-number-of-calls: 5
  timelimiter:
    instances:
      user-service:
        timeout-duration: 2s
